AS	=	ML
ASFLAGS	=	/I. /Zm /c /Fo$@
CPY	=	COPY
RAMDISK	=	E:

..\EXEC\DKLDSV.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\DISKREAD.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\EMEMORY.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\EMSDRV.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\EMSHND.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\FILEIO.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\FLIBREAD.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\DSKCH2.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\DSKCH3.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\DSKWID.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

