AS	=	ML
ASFLAGS	=	/I. /Zm /c /Fo$@
CPY	=	COPY
RAMDISK	=	E:

..\EXEC\CONSOLE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\DATPL3A.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\DATPL4.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\EFECT2.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\EFECT3.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

#..\EXEC\GETARG.OBJ	:	$*.ASM
#	$(AS) $(ASFLAGS) $*.ASM
#	$(CPY) $@ $(RAMDISK)

..\EXEC\GETFONT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\GRPACS.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\GRPPLT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\MACHINE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\MACLIB.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\MGXTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\MIBTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\MIDTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\MINTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\MIWTXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\OVLAP.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PARTST.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PARTT2.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PARTT3.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLSLD5.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLSLD6.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLSLD7.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLTEFC.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLTPAT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLTSET.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\PLTTBL.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\RANDAM.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\STRINGS.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98ADVPL.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98CONSL.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98DSPST.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98GRBIO.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98KEYBO.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98KYLC.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98MOUSE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98TIMER.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VHVLINE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\V98HVLIN.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VIOPORT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VKEYBORD.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VKYLC.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VMOUSE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VMUSCOR.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VMUSCR2.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VRMMOV.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VRMOVE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VRTEXT.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\VTIMER.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\SCROLL.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\XLINE.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\XLINEOR.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

..\EXEC\XLINEMSK.OBJ	:	$*.ASM
	$(AS) $(ASFLAGS) $*.ASM
	$(CPY) $@ $(RAMDISK)

